version: '3.8'
services:
  backup:
    build: .
    container_name: remote-backup
    volumes:
      - ${HOME}:/data/source:ro
      - ./.ssh:/root/.ssh:ro
      - ./backup.conf:/config/backup.conf:ro
